version: '3'

services:
  fast_api:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: 'fastAPI'
    depends_on:
      - mongo
    ports:
      - '8000:8000'
  mongo:
    image: 'mongo'
    restart: always
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD='root_2021'
    volumes:
      - ./compose/local/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo_db:/data/db
    ports:
      - '27017:27017'
